WEB_SERVER_START = 'web_server_start'

ADMIN_AUTH_FAILURE = 'admin_auth_failure'
ADMIN_AUTH_SUCCESS = 'admin_auth_success'
ADMIN_AUTH_REASON_RATE_LIMIT = 'rate_limit'
ADMIN_AUTH_REASON_DISABLED = 'disabled'
ADMIN_AUTH_REASON_INVALID_PASSWORD = 'invalid_password'
ADMIN_AUTH_REASON_INVALID_OTP = 'invalid_otp'
ADMIN_AUTH_REASON_INVALID_YUBIKEY = 'invalid_yubikey'
ADMIN_SESSION_START = 'admin_session_start'
ADMIN_SESSION_END = 'admin_session_end'
