name: pritunl
version: 1.0.0
dependencies:
  angular: ">=1.1.0 <2.0.0"
  web_components: ">=0.10.1"
  browser: ">=0.10.0+2"
  barback: ">=0.14.1"
  logging: ">=0.9.3"
transformers:
- pritunl
- angular
